;========================================================================
;                      Global variables file
;========================================================================
;   All global variables here. They get imported into everything.


[Variables]
var.MediaApp=Spotify
var.MediaPlayerColor=30,215,96,255

var.BlockWidth=48
var.BlockHeight=48
var.BorderWidth=8
var.NotifierHeight=1

var.SkinTransparentColor=0,0,0,1
var.SkinSolidColor=0,0,0,255
var.SkinElementColor=255,255,255
var.SkinColorHighlight=222,79,44

var.FontColor=255,255,255,255
var.FontColorSubtle=150,50,50,255
var.FontColorHilight=#var.SkinColorHighlight#
var.FontColorGrey=150,160,170,150

var.FontFace=Metropolis
var.FontSizeSmall=12
var.FontSizeMedium=18
var.FontSizeLarge=24
var.FontSizeHuge=30

var.PaddingHText=24
var.PaddingHTextSmall=(#var.PaddingHText# - (#var.FontSizeSmall# / 6))
var.PaddingHTextMedium=(#var.PaddingHText# - (#var.FontSizeMedium# / 6))
var.PaddingHTextLarge=(#var.PaddingHText# - (#var.FontSizeLarge# / 6))
var.PaddingHTextHuge=(#var.PaddingHText# - (#var.FontSizeHuge# / 6))

var.PaddingVText=20

var.Shape.Base=Rectangle 0,0,48,48 | Fill Color 0,0,0,1 | StrokeWidth 0

